@startuml
'https://plantuml.com/class-diagram

Operation o-- Circle: Aggregation: area(int radius)

class Circle
  {
  Operation operation
  __
  double pi
  __
  double area(int radius)
  }




class Operation{
square (int n)
}

@enduml